function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function sanitizeName(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

export function generateObjectCode(object, gameData) {
  const className = capitalize(sanitizeName(object.name));
  const states = object.states || [];

  // Collect all unique animations and images used
  const usedAnimations = new Set();
  const usedImages = new Set();
  const usedSounds = new Set();

  states.forEach(state => {
    if (state.visualType === 'animation' && state.visualId) {
      usedAnimations.add(state.visualId);
    } else if (state.visualType === 'image' && state.visualId) {
      usedImages.add(state.visualId);
    }
    if (state.soundId) {
      usedSounds.add(state.soundId);
    }
  });

  // Get animation and image details
  const animations = Array.from(usedAnimations).map(id =>
    gameData.animations.find(a => a.id === id)
  ).filter(Boolean);

  const images = Array.from(usedImages).map(id =>
    gameData.images.find(i => i.id === id)
  ).filter(Boolean);

  const sounds = Array.from(usedSounds).map(id =>
    gameData.sounds.find(s => s.id === id)
  ).filter(Boolean);

  // Build the code
  let code = `-- Object: ${object.name}
-- Generated by Love2D Studio
-- Copy this file to your game's directory

local anim8 = require 'lib.anim8'

local ${className} = {}
${className}.__index = ${className}

function ${className}:new(x, y)
    local self = setmetatable({}, ${className})
    self.x = x or 0
    self.y = y or 0

`;

  // Load sprite sheets for animations
  if (animations.length > 0) {
    code += `    -- Sprite sheets\n`;
    animations.forEach(anim => {
      const varName = sanitizeName(anim.name);
      code += `    self.sheet_${varName} = love.graphics.newImage('assets/animations/${anim.filename}')\n`;
    });
    code += `\n`;

    code += `    -- Animation grids\n`;
    animations.forEach(anim => {
      const varName = sanitizeName(anim.name);
      code += `    local grid_${varName} = anim8.newGrid(${anim.frameWidth}, ${anim.frameHeight}, self.sheet_${varName}:getWidth(), self.sheet_${varName}:getHeight())\n`;
    });
    code += `\n`;
  }

  // Load individual images
  if (images.length > 0) {
    code += `    -- Images\n`;
    images.forEach(img => {
      const varName = sanitizeName(img.name);
      code += `    self.img_${varName} = love.graphics.newImage('assets/images/${img.filename}')\n`;
    });
    code += `\n`;
  }

  // Load sounds
  if (sounds.length > 0) {
    code += `    -- Sounds\n`;
    sounds.forEach(sound => {
      const varName = sanitizeName(sound.name);
      code += `    self.snd_${varName} = love.audio.newSource('assets/sounds/${sound.filename}', 'static')\n`;
    });
    code += `\n`;
  }

  // Create animations table
  if (animations.length > 0 || images.length > 0) {
    code += `    -- State animations/visuals\n`;
    code += `    self.animations = {\n`;
    states.forEach(state => {
      const stateName = sanitizeName(state.name);
      if (state.visualType === 'animation' && state.visualId) {
        const anim = gameData.animations.find(a => a.id === state.visualId);
        if (anim) {
          const animVar = sanitizeName(anim.name);
          code += `        ${stateName} = anim8.newAnimation(grid_${animVar}('1-${anim.frameCount}', 1), ${anim.frameDuration}),\n`;
        }
      }
    });
    code += `    }\n\n`;

    code += `    -- State images (for non-animated states)\n`;
    code += `    self.stateImages = {\n`;
    states.forEach(state => {
      const stateName = sanitizeName(state.name);
      if (state.visualType === 'image' && state.visualId) {
        const img = gameData.images.find(i => i.id === state.visualId);
        if (img) {
          const imgVar = sanitizeName(img.name);
          code += `        ${stateName} = self.img_${imgVar},\n`;
        }
      }
    });
    code += `    }\n\n`;

    // Map states to their sprite sheets
    code += `    -- State sprite sheets (for animated states)\n`;
    code += `    self.stateSheets = {\n`;
    states.forEach(state => {
      const stateName = sanitizeName(state.name);
      if (state.visualType === 'animation' && state.visualId) {
        const anim = gameData.animations.find(a => a.id === state.visualId);
        if (anim) {
          const animVar = sanitizeName(anim.name);
          code += `        ${stateName} = self.sheet_${animVar},\n`;
        }
      }
    });
    code += `    }\n\n`;
  }

  // Create sounds table
  code += `    -- State sounds (play on enter)\n`;
  code += `    self.stateSounds = {\n`;
  states.forEach(state => {
    const stateName = sanitizeName(state.name);
    if (state.soundId) {
      const sound = gameData.sounds.find(s => s.id === state.soundId);
      if (sound) {
        const soundVar = sanitizeName(sound.name);
        code += `        ${stateName} = self.snd_${soundVar},\n`;
      }
    }
  });
  code += `    }\n\n`;

  // Set initial state
  const initialState = states[0] ? sanitizeName(states[0].name) : 'idle';
  code += `    self.currentState = '${initialState}'\n`;
  code += `    \n    return self\nend\n\n`;

  // setState method
  code += `function ${className}:setState(state)
    if self.currentState ~= state then
        self.currentState = state

        -- Reset animation if exists
        if self.animations[state] then
            self.animations[state]:gotoFrame(1)
        end

        -- Play sound if exists
        if self.stateSounds[state] then
            self.stateSounds[state]:stop()
            self.stateSounds[state]:play()
        end
    end
end

`;

  // update method
  code += `function ${className}:update(dt)
    -- Update current animation
    local anim = self.animations[self.currentState]
    if anim then
        anim:update(dt)
    end
end

`;

  // draw method
  code += `function ${className}:draw()
    local anim = self.animations[self.currentState]
    local sheet = self.stateSheets[self.currentState]
    local img = self.stateImages[self.currentState]

    if anim and sheet then
        -- Draw animated state
        anim:draw(sheet, self.x, self.y)
    elseif img then
        -- Draw static image state
        love.graphics.draw(img, self.x, self.y)
    end
end

`;

  code += `return ${className}\n`;

  return code;
}
